from src.api.schemas.search import (
    SearchExecuteRequest,
    SearchExecuteResponse,
    SearchResponseBlock,
    SearchResultItem,
)
from src.config import Settings, get_settings
from src.workflows.search_workflow import run_search_workflow


def build_search_execute_response(
    request: SearchExecuteRequest,
    settings: Settings | None = None,
) -> SearchExecuteResponse:
    cfg = settings if settings is not None else get_settings()
    workflow_output = run_search_workflow(request.query, request.filters)

    query_terms = [term for term in request.query.lower().split() if term][:3]
    if not query_terms:
        query_terms = ["query"]

    result_items = [
        SearchResultItem(
            rank=index,
            result_type="ayah",
            score=hit["score"],
            title=f"Placeholder Ayah Match {index}",
            snippet_text=f"Dummy snippet for term '{hit['term']}'",
            highlighted_text=f"... <mark>{hit['term']}</mark> ...",
            match_metadata={"matched_terms": [hit["term"]]},
            explanation="Placeholder retrieval explanation",
            provenance={"index": "quran-ayah", "ref": hit["ref"]},
        )
        for index, hit in enumerate(workflow_output["vector_hits"], start=1)
    ]

    blocks = [
        SearchResponseBlock(
            order=1,
            block_type="summary",
            title="Summary",
            payload={"text": "Bootstrap placeholder summary"},
            explanation="Summary generated by placeholder workflow",
            confidence=0.83,
            provenance={"component": "summarizer"},
            warning_text="",
            items=[],
        ),
        SearchResponseBlock(
            order=2,
            block_type="result_hits",
            title="Result Hits",
            payload={
                "total_hits": len(result_items),
                "query_terms": query_terms,
            },
            explanation="Hit list generated by placeholder workflow",
            confidence=0.81,
            provenance={"component": "retrieval"},
            warning_text="",
            items=result_items,
        ),
    ]

    return SearchExecuteResponse(
        title=f"Search results for: {request.query}",
        overall_confidence=0.84,
        render_schema_version=cfg.render_schema_version,
        metadata={
            "retrieval_ms": workflow_output["retrieval_ms"],
            "generation_ms": workflow_output["generation_ms"],
            "provider": "internal-placeholder",
        },
        blocks=blocks,
    )
